import { Router } from "express";
import { requireAuth, requireAdmin } from "../middleware/auth.js";
import QuestionPool from "../models/QuestionPool.js";
import { generateCategoryPool } from "../services/questionGenerator.js";

const router = Router();
router.use(requireAuth, requireAdmin);

function todayKey() {
  return new Date().toISOString().slice(0, 10);
}

// GET /api/admin/pools - view today's pool status per category
router.get("/pools", async (req, res) => {
  const date = req.query.date || todayKey();
  const pools = await QuestionPool.find({ date })
    .select("category status generationNotes questions")
    .lean();

  res.json({
    date,
    pools: pools.map((p) => ({
      category: p.category,
      status: p.status,
      questionCount: p.questions.length,
      notes: p.generationNotes,
    })),
  });
});

// POST /api/admin/pools/:category/regenerate - regenerate a single category
router.post("/pools/:category/regenerate", async (req, res) => {
  const date = req.body.date || todayKey();
  const { category } = req.params;

  try {
    const questions = await generateCategoryPool(category);
    const status = questions.length > 0 ? "published" : "failed";

    const updated = await QuestionPool.findOneAndUpdate(
      { date, category },
      { date, category, questions, status, generationNotes: "Manually regenerated by admin" },
      { upsert: true, new: true }
    );

    res.json({ category, status: updated.status, questionCount: updated.questions.length });
  } catch (err) {
    res.status(500).json({ error: "Regeneration failed", details: err.message });
  }
});

// DELETE /api/admin/pools/:category/questions/:qid - flag/remove a bad question
router.delete("/pools/:category/questions/:qid", async (req, res) => {
  const date = req.body.date || todayKey();
  const { category, qid } = req.params;

  const updated = await QuestionPool.findOneAndUpdate(
    { date, category },
    { $pull: { questions: { qid } } },
    { new: true }
  );

  if (!updated) return res.status(404).json({ error: "Pool not found" });
  res.json({ category, remaining: updated.questions.length });
});

export default router;
