import { Router } from "express";
import { requireAuth, requireAdmin } from "../middleware/auth.js";
import QuestionPool from "../models/QuestionPool.js";
import { generateCategoryPool } from "../services/questionGenerator.js";
import { runDailyGeneration } from "../scripts/generateDailyPool.js";
import { CATEGORIES } from "../config/categories.js";

const router = Router();

function todayKey() {
  return new Date().toISOString().slice(0, 10);
}

function checkTriggerKey(req, res) {
  const key = req.query.key || req.headers["x-trigger-key"];
  if (!process.env.TRIGGER_SECRET || key !== process.env.TRIGGER_SECRET) {
    res.status(403).json({ error: "Invalid or missing trigger key" });
    return false;
  }
  return true;
}

// POST /api/admin/trigger-generation?key=... - manually kick off today's pool
// generation over HTTP. Exists because free-tier hosting (Render) has no
// shell/one-off-job access to run the script directly. Protected by a
// shared secret (TRIGGER_SECRET env var), not by user login, since no admin
// account may exist yet on first setup. Safe to remove once cron is proven
// reliable and/or the plan is upgraded to support one-off jobs.
router.post("/trigger-generation", async (req, res) => {
  if (!checkTriggerKey(req, res)) return;

  // Respond immediately; generation takes several minutes so we don't hold
  // the request.
  res.json({ started: true, message: "Daily generation started in background." });

  runDailyGeneration().catch((err) =>
    console.error("[admin] Manual trigger-generation failed:", err)
  );
});

// GET /api/admin/generation-status?key=... - quick check of how many of
// today's 19 categories are published, without needing an admin login.
// Same shared-secret protection as trigger-generation, for the same reason.
router.get("/generation-status", async (req, res) => {
  if (!checkTriggerKey(req, res)) return;

  const date = req.query.date || todayKey();
  const pools = await QuestionPool.find({ date }).select("category status questions").lean();
  const byCategory = Object.fromEntries(pools.map((p) => [p.category, p]));

  const rows = CATEGORIES.map((category) => {
    const pool = byCategory[category];
    return {
      category,
      status: pool?.status || "not_started",
      questionCount: pool?.questions?.length || 0,
    };
  });

  const publishedCount = rows.filter((r) => r.status === "published").length;

  res.json({
    date,
    publishedCount,
    totalCategories: CATEGORIES.length,
    complete: publishedCount === CATEGORIES.length,
    rows,
  });
});

router.use(requireAuth, requireAdmin);

// GET /api/admin/pools - view today's pool status per category
router.get("/pools", async (req, res) => {
  const date = req.query.date || todayKey();
  const pools = await QuestionPool.find({ date })
    .select("category status generationNotes questions")
    .lean();

  res.json({
    date,
    pools: pools.map((p) => ({
      category: p.category,
      status: p.status,
      questionCount: p.questions.length,
      notes: p.generationNotes,
    })),
  });
});

// POST /api/admin/pools/:category/regenerate - regenerate a single category
router.post("/pools/:category/regenerate", async (req, res) => {
  const date = req.body.date || todayKey();
  const { category } = req.params;

  try {
    const questions = await generateCategoryPool(category);
    const status = questions.length > 0 ? "published" : "failed";

    const updated = await QuestionPool.findOneAndUpdate(
      { date, category },
      { date, category, questions, status, generationNotes: "Manually regenerated by admin" },
      { upsert: true, new: true }
    );

    res.json({ category, status: updated.status, questionCount: updated.questions.length });
  } catch (err) {
    res.status(500).json({ error: "Regeneration failed", details: err.message });
  }
});

// DELETE /api/admin/pools/:category/questions/:qid - flag/remove a bad question
router.delete("/pools/:category/questions/:qid", async (req, res) => {
  const date = req.body.date || todayKey();
  const { category, qid } = req.params;

  const updated = await QuestionPool.findOneAndUpdate(
    { date, category },
    { $pull: { questions: { qid } } },
    { new: true }
  );

  if (!updated) return res.status(404).json({ error: "Pool not found" });
  res.json({ category, remaining: updated.questions.length });
});

export default router;
